FROM python:3.11-slim

WORKDIR /app

RUN apt-get update \
 && apt-get install -y --no-install-recommends netcat-openbsd \
 && rm -rf /var/lib/apt/lists/*

COPY requirements-consumer.txt .
RUN pip install --no-cache-dir -r requirements-consumer.txt

COPY src/ ./src
COPY model/catboost_model.pkl ./model/catboost_model.pkl

ENV PYTHONPATH=/app/src

CMD ["sh", "-c", "until nc -z kafka 9092; do echo '⏳ Esperando a Kafka...'; sleep 1; done && python -m model_consumer.consumer"]
